config/routes.rb
Rails.application.routes.draw do
  get 'certifications/index'
  get 'home/index'
  resources :hobbies
  resources :users
  root 'home#index'
  resources :certifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certification.rb
class Certification < ApplicationRecord
    belongs_to :user
    has_one_attached :url
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/hobby.rb
class Hobby < ApplicationRecord
    belongs_to :user
    enum category: [:Musica, :Lectoescritura, :Aventura, :Fitness, :Coleccionismo, :Entretenimiento, :Construccion, :Gastronomia ]

end

app/models/user.rb
class User < ApplicationRecord
    has_many :hobbies
    has_many :certifications
    has_many :friends
    validates_uniqueness_of :email, :user_name
    has_one_attached :profile_pic
    before_create :image_empty
    accepts_nested_attributes_for :hobbies, :certifications, reject_if: :all_blank

    private

    def image_empty
        unless profile_pic.attached?
            self.profile_pic.attach(io: File.open(Rails.root.join("app/assets/images/default.jpg")), filename: 'default.jpg', content_type:"image/png")
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  # before_action :set_certification, only: [:show, :destroy]

  def index
    @certifications = Certification.all
  end
 # GET /hobbies/new
 def new
  @certification = Certification.new
end

# GET /hobbies/1/edit
def edit
end

# POST /hobbies
# POST /hobbies.json
def create
  @certification = Certification.new(certification_params)

  respond_to do |format|
    if @certification.save
      format.html { redirect_to @certification, notice: 'cert was successfully created.' }
      format.json { render :show, status: :created, location: @certification }
    else
      format.html { render :new }
      format.json { render json: @certification.errors, status: :unprocessable_entity }
    end
  end
end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @certification = Certification.find_by(id: params[:id])
    @certification.destroy
    respond_to do |format|
      format.html { redirect_to certifications_url, notice: 'cert  was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_certification
    @certification = certification.find(params[:id])
  end

  def certification_params
    params.require(:certification).permit(:name, :url, :user_id)
  end

end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]

  # GET /hobbies
  # GET /hobbies.json
  def index
    @hobbies = Hobby.all
  end

  # GET /hobbies/1
  # GET /hobbies/1.json
  def show
  end

  # GET /hobbies/new
  def new
    @hobby = Hobby.new
  end

  # GET /hobbies/1/edit
  def edit
  end

  # POST /hobbies
  # POST /hobbies.json
  def create
    @hobby = Hobby.new(hobby_params)

    respond_to do |format|
      if @hobby.save
        format.html { redirect_to @hobby, notice: 'Hobby was successfully created.' }
        format.json { render :show, status: :created, location: @hobby }
      else
        format.html { render :new }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hobbies/1
  # PATCH/PUT /hobbies/1.json
  def update
    respond_to do |format|
      if @hobby.update(hobby_params)
        format.html { redirect_to @hobby, notice: 'Hobby was successfully updated.' }
        format.json { render :show, status: :ok, location: @hobby }
      else
        format.html { render :edit }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hobbies/1
  # DELETE /hobbies/1.json
  def destroy
    @hobby.destroy
    respond_to do |format|
      format.html { redirect_to hobbies_url, notice: 'Hobby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hobby
      @hobby = Hobby.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hobby_params
      params.require(:hobby).permit(:name, :description, :preference, :category)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :age, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @user.hobbies.new
    @user.certifications.new
    # @hobbies = Hobby.new
   
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.save
    # redirect_to users_path  
  
    
    # @user.image.attach(params([:user][:profile_pic]))

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        @user.hobbies.new(user_params[:hobby_attributes])
        @user.certifications.new(user_params[:certifications_attributes])
      end
    end
    
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list sthrough.
    def user_params
      params.require(:user).permit(:name, :lastname, :subtitle, :email, :user_name, :bio, :birthdate, :photo, :profile_pic, hobbies_attributes: [:name, :description, :preference, :category], certifications_attributes: [:name, :url])
    end

    def age

      @age = Date.today.year - @user.birthdate.year 
      @age = 1 if Date.today < @user.birthdate + @age.years
    end
    


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/certifications/_form.html.haml
= form_for @certification do |f|
  - if @certification.errors.any?
    #error_explanation
      %h2= "#{pluralize(@certification.errors.count, "error")} prohibited this certification from being saved:"
      %ul
        - @certification.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_area :url
    -# .field
    -# = f.label :id
    -# = f.text_area :user_id
  

  .actions
    = f.submit 'Save'

app/views/certifications/index.html.haml
%h1 Listing certifications

%table
  %thead
    %tr
      %th Name
      %th certificado
      %th
      %th
      %th

  %tbody
    - @certifications.each do |certification|
      %tr
        %td= certification.name
        %td= certification.name
        %td= link_to 'Show'
        %td= link_to 'Edit'
        %td= link_to 'Destroy', certification, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New cert', new_certification_path

app/views/certifications/new.html.haml
%h1 New cert

= render 'form'

= link_to 'Back', certifications_path

app/views/certifications/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @certification.name
%p
  %b url
  = @certification.url
%p
  %b user
  = @certification.user_id


= link_to 'Edit'
\|
= link_to 'Back', certifications_path

app/views/hobbies/_form.html.haml
= form_for @hobby do |f|
  - if @hobby.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hobby.errors.count, "error")} prohibited this hobby from being saved:"
      %ul
        - @hobby.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :preference
    = f.number_field(:preference, in: 1..5)
  .field
    = f.label :category
    = f.select :category, Hobby.categories.keys.map {|cat| [cat.titleize, cat]}
  

  .actions
    = f.submit 'Save'

app/views/hobbies/edit.html.haml
%h1 Editing hobby

= render 'form'

= link_to 'Show', @hobby
\|
= link_to 'Back', hobbies_path

app/views/hobbies/index.html.haml
%h1 Listing hobbies

%table
  %thead
    %tr
      %th Description
      %th Preference
      %th Category
      %th
      %th
      %th

  %tbody
    - @hobbies.each do |hobby|
      %tr
        %td= hobby.description
        %td= hobby.preference
        %td= hobby.category
        %td= link_to 'Show', hobby
        %td= link_to 'Edit', edit_hobby_path(hobby)
        %td= link_to 'Destroy', hobby, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Hobby', new_hobby_path

app/views/hobbies/new.html.haml
%h1 New hobby

= render 'form'

= link_to 'Back', hobbies_path

app/views/hobbies/show.html.haml
%p#notice= notice

  
%p
  %b Description:
  = @hobby.description
%p
  %b Preference:
  = @hobby.preference
%p
  %b Category:
  = @hobby.category

= link_to 'Edit', edit_hobby_path(@hobby)
\|
= link_to 'Back', hobbies_path

app/views/home/index.html.haml
%h1 Bienvenidos a Hack Profile
%p juanpi es el mejor

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackprofile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :lastname
    = f.text_field :lastname
  .field
    = f.label :subtitle
    = f.text_field :subtitle
  .field
    = f.label :email
    = f.email_field :email
  .field
    = f.label :user_name
    = f.text_field :user_name
  .field
    = f.label :bio
    = f.text_area :bio
  .field
    = f.label :birthdate
    = f.date_select(:birthdate, :start_year => 1940, :end_year => Date.today.year - 10)
  .field
    = f.label :image
    = f.file_field :profile_pic 
  %hr
  %h2 User Hobbies
  - 2.times do 
    = f.fields_for :hobbies do |h|
      .field
        = h.label :category
        = h.select :category, [:Musica, :Lectoescritura, :Aventura, :Fitness, :Coleccionismo, :Entretenimiento, :Construccion, :Gastronomia]
        = h.label :description
        = h.text_area :description
      .field
        = h.label :preference
        = h.range_field :preference, min:0, max:5, step:1
  %hr 
  %h2 Certifications
  .field
    = f.fields_for :certifications do |c|
      = c.label :name
      = c.text_field :name
      = c.label :url
      = c.file_field :url
      -# = c.label :id
      -# = c.text_field :user_id  


  %hr
  .actions
    = f.submit 'Saveee'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Lastname
      %th Subtitle
      %th Email
      %th User name
      %th Bio
      %th Birthdate
      %th Photo
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.lastname
        %td= user.subtitle
        %td= user.email
        %td= user.user_name
        %td= user.bio
        %td= user.birthdate
        %td= link_to 'View Profile',  user.profile_pic
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
.col
  %h1 User
  %p
    - if !@user.profile_pic.attached?
      = link_to image_tag('default.jpg')
    - else
      = link_to image_tag(@user.profile_pic, size: "200x250", alt: 'no se pudo mostrar' )
  %p
    %b Name:
    = @user.name
  %p
    %b Lastname:
    = @user.lastname
  %p
    %b Subtitle:
    = @user.subtitle
  %p
    %b Email:
    = @user.email
  %p
    %b User name:
    = @user.user_name
  %p
    %b Bio:
    = @user.bio
  %p
    %b Age:
    = @age
  %hr
  %h1 Hobbies
  - @user.hobbies.each do |x|
    %p
      %b Category:
      = x.category
    %p
      %b Description:
      = x.description
    %p
      %b Preference:
      = x.preference
  %hr
  %h1 Certification
  - @user.certifications.each do |c|
    %p
      %b Name:
      = c.name
    %p
      %p Certification:
      - if !c.url.attached?
        No Certification
      - else 
        = link_to  'View Certification', c.url, class: 'btn btn-primary'
  -# = link_to 'cert'  
  %hr
  = link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary'
  \|
  = link_to 'Back', users_path, class: 'btn btn-primary'